models:
  embed_model: manutic/nomic-embed-code:7b-Q4_K_M
  qna_model: codestral:22b-v0.1-q2_K
ollama_base_url: "http://localhost:11434"
embedding_chunk_size: 1000  # characters
supported_languages:
  - python
  - javascript
  - go
  - typescript
extensions:
  python: .py
  javascript: .js
  typescript: .ts
  go: .go
chroma_db_dir: "./data/chroma_index"
exclude_patterns:
  - "__pycache__/"
  - "*.egg-info/"
  - "test/"
  - "prompt/"
  - "data/"
  - ".git/"
  - ".venv/"
  - "env/"
  - "build/"
  - "dist/"
  - "*.lock"
  - "node_modules/"
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "vite.config.*"
  - "next.config.*"
  - "webpack.config.*"
  - "babel.config.*"
  - "vendor/"
  - "target/"
  - "LICENSE"
  - "license*"
  - "__init__.py"
  - "__init__.pyc"
  - "__init__.pyo"
  - "__init__.pyw"
  - "__init__.cpython-*"
  - "__main__.py"
  - "__main__.pyc"
  - "__main__.pyo"
  - "__main__.pyw"
  - "__main__.cpython-*"
  - "__about__.py"
  - "__version__.py"
  - "__meta__.py"
  - "__init__.rb"
  - "__init__.js"
  - "__init__.ts"
